spring:
  application:
    name: greeting-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-microservice:
  greeting: "Olá a todos"
  default-value: "parece que foi!"
