spring:
  application:
    name: greeting-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-microservice:
  greeting: "Greting do arquivo perf"
  default-value: "hehheeh"
